### ISSUE TITLE
Multiple implementations and namespacing

### ISSUE THREAD

**Issue by simonbyrne** [JuliaMath/Libm.jl#13]
As we proceed we're going to end up with multiple implementations of some functions (until we can decide which is best). We need to figure out a way to namespace these to avoid conflicts.

Two options that I can think of:
- Suffix the function names with the source: e.g. `exp_musl`
- Use modules: e.g. `Libm.Musl.exp`

Thoughts?

**Comment by tkelman** [comment]
+1 for using modules

**Comment by oxinabox** [comment]
I thought git branches might be the way to go.
But that doesn't really let you have two things at once and let you compare them.
So modules are probably best.

**Comment by musm** [comment]
Closing since we have agreed to use modules.
