### ISSUE TITLE
Strategy for accuracy testing

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaMath/Libm.jl#16]
For single-argument `Float32` functions, one can exhaustively test the entire range. It seems like we should do that. For `Float16` (supposing we support that, see #15), one can even test two-argument functions exhaustively. There should be a strategy for testing all the libm functions for accuracy. Known hard values + random sampling? For two-arg `Float32` functions, we could use a sample of values for each argument and test the full range of the other argument against that.

**Comment by ViralBShah** [comment]
I believe @simonbyrne had done this for `log`. It's not in the tests, as I see, but I do remember discussion about that in the julialang repo.

**Comment by oxinabox** [comment]
[Sleef does Accuracy testing against MPFR](https://github.com/shibatch/sleef/blob/master/tester/tester.c)
over targetted (large) ranges, determined per function eg `[-10:0.0002:10; -10_000_000:200.1:10_000_000; 1:10_000]`
Plus targeted tests around things like NaN and Inf

@musm has already ported many (all?) of those :+1:
- https://github.com/musm/Libm.jl/blob/2903e319b482c1aacf759af6d462e978fcd438cb/test/runtests.jl
- https://github.com/musm/Libm.jl/blob/2903e319b482c1aacf759af6d462e978fcd438cb/test/dnml_nan.jl
- https://github.com/musm/Libm.jl/blob/2903e319b482c1aacf759af6d462e978fcd438cb/test/accuracy.jl
- https://github.com/musm/Libm.jl/blob/2903e319b482c1aacf759af6d462e978fcd438cb/test/accuracy_base.jl

And it would not be hard to generalise those test files. to work for other LibM implementations.

Do we need more than this?

Maybe Fuzzer tests?

**Comment by ViralBShah** [comment]
For `Float32`, we could perhaps test the whole range, but that may be overkill. Perhaps some thought should be put into ill-conditioned cases.

**Comment by musm** [comment]
Yes all of them have been ported plus a couple of additional ones I noticed Sleef did not test for
