### ISSUE TITLE
erf and erfc based on sleef principles

### ISSUE THREAD

**Issue by musm** [JuliaMath/Libm.jl#22]
@shibatch it would be fantastic if you would like to collaborate on developing `erf` and `erfc` functions based on  Sleef principles? These are pretty critical functions for multiple reasons and it would be great to have a pure julia implementation (the musl code while is within <2 times the speed of openlibm can be improved upon greatly).

**Comment by shibatch** [comment]
Basically, I am quite busy and I cannot guarantee how much contribution I will be able to make, but I will try.

**Comment by shibatch** [comment]
This thing is in my TODO list. I will do it eventually.

**Comment by shibatch** [comment]
@musm I finished implementing erf, erfc, lgamma and tgamma.
https://github.com/shibatch/sleef/tree/Introducing_erf_and_gamma

**Comment by musm** [comment]
ok thanks, I need to update Sleef.jl with all the changes.
