### ISSUE TITLE
benchmark results repository

### ISSUE THREAD

**Issue by musm** [JuliaMath/Libm.jl#34]
Feel free to post results of running the benchmarks suite, including  `versioninfo()` and commit number for reference

**Comment by ChrisRackauckas** [comment]
High-Powered Dual Xeon(R) CPU E5-2667 v4 @ 3.20GHz: 
https://gist.github.com/ChrisRackauckas/fb2c187317af097c61f03e7d99b71bb2

**Comment by ChrisRackauckas** [comment]
AMD FX-8350:
https://gist.github.com/ChrisRackauckas/97906a7ead17da9b08377bccec552af0

**Comment by ChrisRackauckas** [comment]
Overclocked i7 4770K:
https://gist.github.com/ChrisRackauckas/68a8a77f4e9cca42a611e8e2e4a0c534

**Comment by musm** [comment]
As always thanks @ChrisRackauckas . I addressed the perf of the inverse trig functions and exp# functions, and hopefully a bit of the cbrt.

**Comment by KristofferC** [comment]
https://gist.github.com/KristofferC/99d9eec3b4c6f7522cf8334306063316

```
julia> versioninfo()
Julia Version 0.6.0-dev.736
Commit 32c1a31* (2016-09-21 21:04 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, sandybridge)
```

commit:  d2b90b6bb532d73ef48b

**Comment by musm** [comment]
Thanks @KristofferC  I just merged https://github.com/JuliaMath/Libm.jl/pull/43 which I hope will bring most things to within 2.5

**Comment by musm** [comment]
Nonetheless results don't look bad at all, I'm hoping https://github.com/JuliaLang/julia/pull/18632 will also help perf, but my understanding is that simple immutables are already stack allocated, but perhaps not inlined into arrays ?

**Comment by ChrisRackauckas** [comment]
Yes, immutables are already stack allocated for simple immutables. Maybe that helps Complex? 

Running a new one right now.

**Comment by ChrisRackauckas** [comment]
New Xeon Benchmark:
https://gist.github.com/ChrisRackauckas/84ecbc26a244f0319b6a85c7e3f539e1

**Comment by KristofferC** [comment]
That pr should do nothing for performance here.

**Comment by musm** [comment]
Thanks for the clarification @KristofferC , that's what I figured.

**Comment by pfitzseb** [comment]
i5-4570
https://gist.github.com/pfitzseb/6c0851e3fb41c8565d425b088e4aaa04

**Comment by musm** [comment]
@pabloferz  is that with a custom sys image?
