### ISSUE TITLE
Argument reduction for large trig function argument values

### ISSUE THREAD

**Issue by simonbyrne** [JuliaMath/Libm.jl#39]
```
julia> Libm.Sleef.xsin(96079.33f0)
2.1360017f-7

julia> Libm.Sleef.xsin(Float64(96079.33f0))
-2.6335338809697436e-7
```

**Comment by simonbyrne** [comment]
You shouldn't need Payne-Hanek for this, I think it should be possible within the existing Cody-Waite reduction.

**Comment by musm** [comment]
Do you mean by splitting 4/pi  it into more than four parts?

**Comment by simonbyrne** [comment]
No, but you could do it using `Float64`s: the musl code pattern is a good one:
https://git.musl-libc.org/cgit/musl/tree/src/math/__rem_pio2f.c#n51

**Comment by simonbyrne** [comment]
is this fixed?

**Comment by musm** [comment]
I'ts not an issue here since I haven't added trig functions yet, I moved this issue over to the Sleef repo where it applies (also reported upstream)

**Comment by simonbyrne** [comment]
Ah, I see.
