### ISSUE TITLE
How to handle domain errors? C or Julia convention

### ISSUE THREAD

**Issue by musm** [JuliaMath/Libm.jl#48]
Should we follow the c convention here or the Julia convention of throwing `throw(DomainError())`.

I'm in favor of maintaining the c convention and wrapping in macro calls the Domain Errors as we now do. I'd imagine this would make things more useful in the future when   linking julia code.

**Comment by ararslan** [comment]
Personally I'd vote for `throw(DomainError())`, since it's the Julia convention and this is a pure Julia libm. 😄

**Comment by musm** [comment]
One benefit of handling them as currently done, is that different math library backends can be switched out in make files; should a user prefer openlibm instead of Libm.jl.

**Comment by ChrisRackauckas** [comment]
I think one thing that's important is, not matter how Libm.jl is made, it should be "easy" to swap it out for things like the Intel-optimized LibM because many people will want to build Julia with MKL + VSL + Intel LibM for maximum performance.

**Comment by simonbyrne** [comment]
One option is to do something like:

``` julia
if x < 0
    domerr()
    return NaN
end
```

where `domerr()` can be redefined easily in the top file if need be (could also use a macro if you want to ensure that the function is the top of the trace).

I don't think this will be a problem for switching, as we can do something like

``` julia
if libm != ""
    ($f)(x::Float64) = nan_dom_err(ccall(($(string(f)),libm), Float64, (Float64,), x), x)
    ($f)(x::Float32) = nan_dom_err(ccall(($(string(f,"f")),libm), Float32, (Float32,), x), x)
else
    import Libm.$f
end
```

**Comment by musm** [comment]
I think I'll  go with domain errors, I can refactor later for other use cases.
