### ISSUE TITLE
Design principles for the new Julia mlib

### ISSUE THREAD

**Issue by musm** [JuliaMath/Libm.jl#53]
So I'm working on a new iteration of the library. 

The new library will have native Float16 support (for v0.6)  (In the long term, hopefully we can also have support for Float80, Float128, and Double arithmetic types ... dispatch should make this relatively easy, with the hard part being coefficient generation and developing good approximants and testing accuracy.)

The gist of is the following:
- Sleef is very slow on non-fma systems due to double-double arithmetic. 
- Sleef also adheres to the principles of only using polynomial approximants due to the fact that  multiplication and addition operations are usually pipelined and can execute every cycle, whereas division and square root occupy   many cycles  and  new operation can start only after the previous ones have finished.
- ... because of this principle  the use of double-double arithmetic is necessary in Sleef  to achieve accuracy within 1 ulp , since it's hard to achieve accuracy within 1 ulp using polynomial approximants. 

Hence the need for rational approximants, which I believe will avoid the necessity of double-double arithmetic while achieving accuracy within 1 ulp (Cephes and Muscl go this route for several of the functions I have looked at).

The question is, should we go this route? Or should we just default to slow performance on systems without hardware fma? I guess we could also default to different code for systems without hardware fma (i.e. default to the rational approximations, except this will add a lot more code that needs to be maintained). Now on the other hand, hardware fma is pretty relevant these days, so that's another thing to think about.

A short list of FMA supported cpus can be found: https://en.wikipedia.org/wiki/Multiply%E2%80%93accumulate_operation

Thoughts?

@simonbyrne @ViralBShah 

Another point is avoiding unpredictable branching. Branching for exceptional cases is fine since it's predictable, however for non exceptional cases we probably have to employ some clever bit hacks and such.
An example of of this is here: https://github.com/JuliaMath/Libm.jl/pull/51/commits/4ca0642d328d2bf858736a6b4cbe0e5e3baefc27#diff-67692d748834cd9dadffa26fd48fc4b7R55

It may be difficult to figure out similar tricks for all functions, if possible, but an example that I managed to get working is the one attached.  I believe this is especially important for gpu code  (cc: @vchuravy  @maleadt) I'm not sure how bad divisions on the gpu are, but for Float16, it's probably easy enough to just use polynomials and still get enough accuracy.

---

**Proposed, opinionated principles** 

Largely inspired by Yeppp and Sleef
1. Try to avoid divisions (i.e. avoid rational approximations) and use polynomials if at all possible
2. Avoid table lookups 
   - (important for vector elementary functions, although we do not purport to do any special at this point for vector inputs; for scalar inputs, table lookups may be faster than evaluating a polynomial; a  case in point is openlibm's exp2 functions)
   - Helpful for generic implementations to avoid table look ups
   - Tables for large float types also don't make much sense
3. Avoid unpredictable branches. (branches for exceptional user inputs are ok).
4. Take advantage of FMA instructions
5. Accuracy within 1 ulp 
6. Try to avoid double-double arithmetic if at all possible under accuracy constraints.
   - Difficult but I was able to get the atan function (notoriously difficult) to be almost within 1.25 ulps, through better coefficients. 

_Tradeoffs_ 
- Will be about 10 times slower on systems without hardware fma
- For exceptional user input, i.e. Inf, NaN, and large argument/small arguments to exponential functions adhering to principle 3 will mean these will be slower than openlibm since we try take advantage of automatic overflow. In these exceptional cases, the branched version is usually faster, but this is a sacrifice we make for fast functions in regular domains. 
- See point 2. this a tradeoff where we may sacrifice some speed for scalar inputs

**Comment by TotalVerb** [comment]
Two cents:
- We want results that are more precise and closer to being reproducible, and fma is better than muladd at that. Floating point computations will never be perfectly reproducible but that doesn't mean there shouldn't be an attempt made.
- Most people who need super-fast speed will run on big hardware, which almost certainly has fma. Non-fma hardware is probably on its way out anyway.

**Comment by ChrisRackauckas** [comment]
As far as reproducibility, `fma` instead of `muladd` will produce the same results on any machine. That's something to consider as well. But how slow is `fma` in software? Like, really noticeably bad? It's easy for me to just say "push forward!" since I'm using nice funded lab machines, but this may make the experience really bad for others if Libm.jl is looking to be the standard Libm for Julia.

**Comment by ChrisRackauckas** [comment]
Another thing to consider is that newer hardware like Xeon Phis and newer Xeon chips are really pushing forward in making faster / more SIMD-parallel FMA instructions (I think GPUs as well?), so if the compilers keep up then this path will continue to get better.

**Comment by vchuravy** [comment]
With regards to FloatingPoint support on nvidias GPU's http://docs.nvidia.com/cuda/floating-point/ and http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#maximize-instruction-throughput (The numbers are throughput so bigger is better) and division is supposed to be 4x more expensive that multiplication.

**Comment by vchuravy** [comment]
Also with regards to branch-free: As long as both branches are cheap to compute it is better to use `ifelse` over `&&`

**Comment by musm** [comment]
@vchuravy  In other words just use

``` julia
x = ifelse(n & 1 != 0, -x, x)
u = ifelse(n & 1 != 0, 1/u, u)
```

vs the unreadable

``` julia
 x *= T(1.0) - T(2.0)*(n & 1) 

u = (1-(n & 1))*u + (n & 1)*(T(1.0)/(u+realmin(T)))
```

**Comment by vchuravy** [comment]
@musm That's tricky :) The original code is completely branch free and so is probably cheaper than `ifelse(cond, x1, x2)` because the cost of a ifelse is x1+x2+cond+select wich might be costlier than  the original code.

**Comment by musm** [comment]
@vchuravy interesting on the gpu throughput of the div instruction. On my haswell a division 10-24 times the throughput of a single multiply.

**Comment by ViralBShah** [comment]
I think this is a pretty good and well-thought out design, based on the recent experiences.

The question for systems without FMA is, how much slower will this implementation be compared to the system's libm or openlibm. If we are within a factor of 2 of those, that should be fine. Also, we should make it so that any libm can be easily plugged into Julia - so that people on systems without FMA can pick something else.

**Comment by musm** [comment]
@ViralBShah  It looks like it's no slower than 7-8 x openlibm, a healthy number of functions are 2-3 times slower.

**Comment by ViralBShah** [comment]
I think we should build for FMA and the highest speed on recent and upcoming architectures. There are many alternatives for the older hardware and even Amal.jl may be good enough.

@simonbyrne and others - Thoughts?
